### PR TITLE
Add notification.mp3 to support IE

### PR DESCRIPTION
**Pull request by garysharp**
Internet Explorer [doesn't support](http://en.wikipedia.org/wiki/Html5_audio#Supported_audio_codecs) the WAV PCM format in `audio` tags. This PR contains `notification.mp3` (which was converted from `notification.wav`) and updates the `#notificationSound` `audio` tag to use this format if the browser prefers.

### CODE REVIEW

**Comment by hnrkndrssn** [comment]
According to this page http://www.w3schools.com/tags/tag_audio.asp the mime type for mp3 audio is 'audio/mpeg', will 'audio/mp3' still work?

**Comment by garysharp** [comment]
> the mime type for mp3 audio is 'audio/mpeg', will 'audio/mp3' still work?

Looks to be some conflicting advise on this throughout the internet. VS tooling (and elsewhere) suggested `audio/mp3`, various other sources suggest `audio/mpeg` as you say.

Also conflicting advise on PCM WAVE format, some say `audio/wav`, others `audio/wave`. Mozilla [weighs in](https://developer.mozilla.org/en-US/docs/HTML/Supported_media_formats) by _preferring_ `audio/wave` - perhaps this is the way to go?

Testing revealed that both mime-types worked in IE 11 (uses mp3), Chrome 34 (uses wav), and Firefox 29 (uses wav).

**Comment by garysharp** [comment]
Updated mime-types:

> `audio/mp3` -> `audio/mpeg`
> `audio/wav` -> `audio/wave`

**Comment by cmaish** [comment]
Looks and sounds good to me :shipit: IMO

**Comment by davidfowl** [comment]
:shipit:

**Pull request merged**
