### PR TITLE
added Ban command

### PR DESCRIPTION
**Pull request by phillip-haydon**
Ok at long last I'm trying again.

This is what I was trying to comment last month, except now the ChatService no longer thinks every line changed. Using VS 2012 rather than 2010. That's the only difference.

Can now:

/ban _name_ 

Anyone, except me... :D

We can test by banning Daanl.

### CODE REVIEW

**Comment by samandmoore** [comment]
what's with the ban user resx file?

**Comment by phillip-haydon** [comment]
That is what was generated by the migration crap for EntityFailwork.

**Comment by samandmoore** [comment]
@phillip-haydon i figured as much, but none of the other migrations generated that file. I'm guessing this has to do with VS2012. I guess we can just leave it.

**Comment by phillip-haydon** [comment]
It's the first time I've done a migration with VS2012 so I don't know. 

I thought it was strange so I deleted the database and re-built and the database was created correctly so I assumed it was correct.

**Comment by samandmoore** [comment]
we need to ensure that a user cannot log-in via the janrain route, not just via /nick

**Pull request merged**
