### PR TITLE
I don't always get new commands, but when I do, it's a MEME command.

### PR DESCRIPTION
**Pull request by PureKrome**
Hi David. First pass at adding a simple meme command.
### MEME COMMAND

usage: `/meme <meme-type> <top-line> <bottom-line>`
eg: `/meme aa Why-is-JabbR-offline? Aliens`

Included are some unit tests and a simple method which ends up calling the `Send(..)` method.

SIDE QUIRK: I noticed the test classes in `JabbR.Tests` where missing the 's' so I added that.

### CODE REVIEW

**Comment by DavidChristiansen** [comment]
Why so many checkins!? Did you fetch/pull/stretch/relax/pontificate prior to pushing?

**Comment by PureKrome** [comment]
:cry: I donno. i just forked Jabbr. then switched to dev. did code. when to push and it said i was behind. pulled. tested again. then pushed :cry: :cry: :cry:

I just thought that was the state of upstream/dev ?

**Comment by damianh** [comment]
This might be the most important feature added to Jabbr since it was moved to azure for scale out and stability purposes.. oh wait

**Comment by DavidChristiansen** [comment]
I propose the command be

```
/meme <graphic> <First Line, single word or quoted> <Second Line, single word or quoted>
```

example

```
/meme aa "Why is JabbR down again?" Aliens
```

**Comment by DavidChristiansen** [comment]
Also, I would try fix this PR to be JUST your checkins, otherwise you have little chance of it being accepted.

**Comment by Buildstarted** [comment]
The dashes instead of spaces is very wrong. Users should not be required to conform to upboat.me just to add a meme, it should be much more natural. a single separator or quotes should be used to delineate between lines.

and-you-should-feel-bad

**Comment by davidfowl** [comment]
Wow, epic fail PR. Redo.

**Comment by PureKrome** [comment]
Ok guys. For the "top line" "bottom line", gimme some code that JOINS the space delimited string (args) then splits up into those parts, looking for a start and end quote.

**Comment by PureKrome** [comment]
Bah. it's 1:40am. :crescent_moon:  I tried. failed. Someone else do it instead.

I suck

**Comment by damianh** [comment]
@PureKrome Lrn2rebase (I guess)

**Pull request closed without merging**
