### PR TITLE
HADDDOUUKEN - You know you want to

### PR DESCRIPTION
**Pull request by NTaylorMullen**
Secret command:
/hadouken

### CODE REVIEW

**Comment by PureKrome** [comment]
LoL :thumbsup:

**Comment by ajbeaven** [comment]
should be /ddff+p (Down, Down-Forward, Forward + Punch)

**Comment by samandmoore** [comment]
Damian brought up a good point: this would be better if it worked like the nudge command. i.e. it needs to show up for all users in a specific room when the command is called.

**Comment by NTaylorMullen** [comment]
Definitely a great plan =).  Not too hard to do either, especially seeing since a lot of the user friendly functionality is already there via nudge.

One issue though is getting images that are not copyrighted etc.  The sound is copywrite safe but the images I'll have to do some research into, I just got em off of Google images.

**Comment by samandmoore** [comment]
@NTaylorMullen yeah, that's why it was never merged in the first place. I dunno enough about the copyright stuff to safely accept it ;)

**Pull request closed without merging**
