### PR TITLE
Rooms can show or hide any connection messages :alien:

### PR DESCRIPTION
**Pull request by PureKrome**
Reference: [Issue #695](https://github.com/davidfowl/JabbR/issues/695)
- Rooms have an IsConnectionDisplayed boolean property.
- New ToggleConnectionMessage admin/room owner command.
- Connection messages are displayed or muted, depending on the room IsConnectionMessageDisplayed state.
- Database migration included to update the ChatRooms table.

### CODE REVIEW

**Comment by PureKrome** [comment]
(I wasn't sure how I can PR this into a new branch in your repo).

**Comment by davidfowl** [comment]
I need a picture.

**Comment by PureKrome** [comment]
I've [made a quick YouTube video](http://www.youtube.com/watch?v=fIyx2J3OvJ8) showing 2 jabbr instances, open.

There's one bug i'll fix up, this arvo/evening (the bug is displayed in the vid). but at least the video shows you clearly, how this works.

Is this ok? (besides that incorrect UI message?)

**Comment by PureKrome** [comment]
PR updated with my bugfix :shipit:

**Pull request closed without merging**
