### PR TITLE
Custom error page

### PR DESCRIPTION
**Pull request by cmaish**
This one's been sitting around for a while.  

Add an error page, make it suggest rooms if you try to access site.com/roomName and it's a 404.

### CODE REVIEW

**Comment by xt0rted** [comment]
Since you can link to rooms like so `https://jabbr.net/#/rooms/meta` what about handling the format `https://jabbr.net/rooms/meta` as well?

**Comment by cmaish** [comment]
Should be ready to go now.

**Comment by hnrkndrssn** [comment]
Looks good to me :+1:

**Comment by cmaish** [comment]
Should be good to merge on the new dev!

**Comment by davidfowl** [comment]
pics of the error page

**Comment by cmaish** [comment]
croppercapture 4

The suggestion line only shows when you've entered a room-like url.  The 404 - NotFound is the code and Enum value that nancy gives us.

**Pull request merged**
