### PR TITLE
Nudge Notifications

### PR DESCRIPTION
**Pull request by mrb0nj**
When nudging a User play an audio and/or display toast notification if enabled in any room. This should grab the users attention when out of browser.

I'm fairly new to JabbR so not sure if this is the best way? feedback welcomed :)

### CODE REVIEW

**Comment by cmaish** [comment]
Nice PR - Clean and works well.  Based on how the code is structured at the moment, it's the right way to do things too, IMO.

**Comment by davidfowl** [comment]
Looks good.

**Comment by hnrkndrssn** [comment]
thank-you-spice

**Comment by mrb0nj** [comment]
Many thanks, glad I was on the right track :)

**Pull request merged**
