### PR TITLE
Add room allowance for user max 5, update addRoom service to check room ...

### PR DESCRIPTION
**Pull request by jharjadi**
...allowance. [#231]

Add max-weight for image in the collapsible-box (prevent displaying super big image)

### CODE REVIEW

**Comment by davidfowl** [comment]
So once I hit the limit I can never create another room?

**Comment by davidfowl** [comment]
Before accepting this we'd need to have the ability to close rooms.

**Comment by jharjadi** [comment]
Will need admin function/command to be able to set this RoomAllowance.

**Comment by davidfowl** [comment]
That's orthogonal to this but yes, we'll need that as well. Anyway this feature is premature, we need other features to make this work well.

**Pull request closed without merging**
