### PR TITLE
Fix csrf validation

### LINKED ISSUE #1093: CSRF token not validated
Signin page (among others) has a CSRF token embedded in the form (Html.AntiForgeryToken) but it's never checked.  We should probably call ValidateCsrfToken somewhere.

### PR DESCRIPTION
**Pull request by cmaish**
Adds validation for CSRF tokens.  Fixes #1093

When combined with #1115, looks like:

capture 25

### CODE REVIEW

**Comment by hnrkndrssn** [comment]
:thumbsup: looks good to me

**Comment by davidfowl** [comment]
@cmaish Check JabbR.Client

**Comment by cmaish** [comment]
I'm thinking that we can solve that by checking for a Sec- header
(Sec-Jabbr-Client?), which, if present will skip the CSRF token check.
 This way, we've got protection against ajax-based posting, but it's pretty
straightforward to use non-browser-based clients to connect to jabbr.

Will update to show what I mean when I get the chance.

**Comment by davidfowl** [comment]
@cmaish yep

**Comment by cmaish** [comment]
Should be ready to go now.  _Note that this does break existing clients_ - they need to send the sec-jabbr-client header (or a valid CSRF token) or they'll get errors.

**Comment by davidfowl** [comment]
This will break older clients

**Comment by cmaish** [comment]
useragents containing "signalr" and also useragents which do not report headers are now exempt from the CSRF check.  Newer agents could (and should) still use the sec-jabbr-client header, but this allows for older agents to not be broken.

**Comment by cmaish** [comment]
Just in case a client cannot be upgraded, I've added an admin option that allows the user to disable the CSRF check at a server level.
capture 40

**Comment by cmaish** [comment]
Reverted the change for the admin option, we should have CSRF always validated and just tell people to update their bots.

**Pull request merged**
